on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: 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
          project-name: Penn-Connect
          column-name: To Do
